//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veiled_Kashmir_Admin_Panel
{
    using System;
    using System.Collections.Generic;
    
    public partial class place
    {
        public long pid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public bool explored { get; set; }
        public string hotspot { get; set; }
        public string hotels { get; set; }
    }
}
