//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veiled_Kashmir_Admin_Panel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string username { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string country { get; set; }
        public string contact { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string pic { get; set; }
    }
}
